FROM golang:alpine  AS builder

WORKDIR /go/src/app

COPY . .

RUN go mod init app/hello

RUN go build -ldflags "-s -w" -o hello

FROM scratch

COPY --from=builder  /go/src/app/hello /hello

ENTRYPOINT ["/hello"]